PROD_PAGE_TITLE = 'css:.page-title'
PROD_CREATE_BTN = 'css:button[onclick*="openModal(\'create\')"]'
PROD_MODAL_FORM = 'id:modal-form'
PROD_F_NAME = 'id:f-name'
PROD_F_CATEGORY = 'id:f-category'
PROD_F_UNIT = 'id:f-unit'
PROD_F_PRICE = 'id:f-price'
PROD_SUBMIT_BTN = 'id:btn-submit'
PROD_CANCEL_BTN = 'css:button[onclick="closeModal()"]'
PROD_SEARCH_INPUT = 'css:input[name="search"]'
PROD_TABLE_ROWS = 'css:table tbody tr'
